on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - 'TODO'          # Push events to every tag not containing TODO

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: katyo/publish-crates@v1
        with:
            CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
